# Generated by Django 4.2.4 on 2023-08-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_note_delete_secretmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="passkey",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
