# Generated by Django 4.2.4 on 2023-08-21 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0003_note_passkey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="passkey",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="key", to="notes.secretkey"
            ),
        ),
    ]
