# Generated by Django 4.2.4 on 2023-08-21 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0004_alter_note_passkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="secretkey",
            name="note",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, related_name="note", to="notes.note"
            ),
            preserve_default=False,
        ),
    ]
