# Generated by Django 4.2.4 on 2023-08-21 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0005_secretkey_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="passkey",
        ),
    ]
