# Generated by Django 4.2.4 on 2023-08-21 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0006_remove_note_passkey"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="secretkey",
            name="note",
        ),
        migrations.AddField(
            model_name="note",
            name="passkey",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, related_name="passkey", to="notes.secretkey"
            ),
            preserve_default=False,
        ),
    ]
